//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anfitriones
    {
        public Anfitriones()
        {
            this.Ordenes = new HashSet<Ordenes>();
        }
    
        public int IdAnfitrion { get; set; }
        public string Codigo { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
    
        public virtual ICollection<Ordenes> Ordenes { get; set; }
    }
}
