//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstadosSolicitud
    {
        public EstadosSolicitud()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
        }
    
        public int IdEstadoSolicitud { get; set; }
        public string NombreEstadoSolicitud { get; set; }
    
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
    }
}
