//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incidencias
    {
        public int IdIncidencia { get; set; }
        public int NumeroPedido { get; set; }
        public int IdTipoIncidencia { get; set; }
        public int IdEstadoIncidencia { get; set; }
        public bool Estado { get; set; }
        public string Detalle { get; set; }
    
        public virtual EstadosIncidencia EstadosIncidencia { get; set; }
        public virtual TiposIncidencia TiposIncidencia { get; set; }
    }
}
