//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesas
    {
        public Mesas()
        {
            this.Ordenes = new HashSet<Ordenes>();
        }
    
        public int IdMesa { get; set; }
        public string Cliente { get; set; }
        public Nullable<int> IdAnfitrion { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public bool Estado { get; set; }
        public string NombreMesa { get; set; }
        public bool EstadoOrden { get; set; }
    
        public virtual ICollection<Ordenes> Ordenes { get; set; }
    }
}
