//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SisresEntities : DbContext
    {
        public SisresEntities()
            : base("name=SisresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Insumos> Insumos { get; set; }
        public DbSet<Pedidos> Pedidos { get; set; }
        public DbSet<Prioridades> Prioridades { get; set; }
        public DbSet<EstadosSolicitud> EstadosSolicitud { get; set; }
        public DbSet<Solicitudes> Solicitudes { get; set; }
        public DbSet<Anfitriones> Anfitriones { get; set; }
        public DbSet<Mesas> Mesas { get; set; }
        public DbSet<Recetas> Recetas { get; set; }
        public DbSet<TiposReceta> TiposReceta { get; set; }
        public DbSet<Carta> Carta { get; set; }
        public DbSet<InsumosPorReceta> InsumosPorReceta { get; set; }
        public DbSet<tb_UnidadMedida> tb_UnidadMedida { get; set; }
        public DbSet<Ordenes> Ordenes { get; set; }
        public DbSet<EstadosIncidencia> EstadosIncidencia { get; set; }
        public DbSet<Incidencias> Incidencias { get; set; }
        public DbSet<TiposIncidencia> TiposIncidencia { get; set; }
    }
}
