//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordenes
    {
        public int IdOrden { get; set; }
        public int IdMesa { get; set; }
        public int IdAnfitrion { get; set; }
        public bool Estado { get; set; }
        public int IdReceta { get; set; }
        public int Cantidad { get; set; }
        public int NumeroPedido { get; set; }
    
        public virtual Anfitriones Anfitriones { get; set; }
        public virtual Mesas Mesas { get; set; }
        public virtual Recetas Recetas { get; set; }
    }
}
