//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        public int IdPedido { get; set; }
        public int IdMesa { get; set; }
        public int IdSilla { get; set; }
        public int IdReceta { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public bool Estado { get; set; }
    }
}
