//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitudes
    {
        public int IdSolicitud { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdEstadoSolicitud { get; set; }
        public int IdInsumo { get; set; }
        public int CantidadSolicitada { get; set; }
        public int CantidadRecibida { get; set; }
        public bool Estado { get; set; }
    
        public virtual EstadosSolicitud EstadosSolicitud { get; set; }
        public virtual Insumos Insumos { get; set; }
    }
}
