//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposReceta
    {
        public TiposReceta()
        {
            this.Recetas = new HashSet<Recetas>();
        }
    
        public int IdTipoReceta { get; set; }
        public string NombreTipoReceta { get; set; }
    
        public virtual ICollection<Recetas> Recetas { get; set; }
    }
}
