//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carta
    {
        public int IdCarta { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdReceta { get; set; }
        public bool IsOferta { get; set; }
        public decimal PrecioOferta { get; set; }
        public bool Estado { get; set; }
    
        public virtual Recetas Recetas { get; set; }
    }
}
