//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        public Insumos()
        {
            this.Solicitudes = new HashSet<Solicitudes>();
            this.InsumosPorReceta = new HashSet<InsumosPorReceta>();
        }
    
        public int IdInsumo { get; set; }
        public string NombreInsumo { get; set; }
        public int StockNormal { get; set; }
        public int StockMinimo { get; set; }
        public int IdPrioridad { get; set; }
        public Nullable<int> CantidadSolicitada { get; set; }
        public Nullable<int> CantidadRequerida { get; set; }
        public Nullable<int> StockActual { get; set; }
        public bool Estado { get; set; }
        public int CODIGO { get; set; }
    
        public virtual Prioridades Prioridades { get; set; }
        public virtual ICollection<Solicitudes> Solicitudes { get; set; }
        public virtual ICollection<InsumosPorReceta> InsumosPorReceta { get; set; }
        public virtual tb_UnidadMedida tb_UnidadMedida { get; set; }
    }
}
