//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sisres.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiposIncidencia
    {
        public TiposIncidencia()
        {
            this.Incidencias = new HashSet<Incidencias>();
        }
    
        public int IdTipoIncidencia { get; set; }
        public string NombreTipoIncidencia { get; set; }
    
        public virtual ICollection<Incidencias> Incidencias { get; set; }
    }
}
